### ISSUE TITLE
OLS version 1.6.12

### ISSUE THREAD

**Issue by publicarray** [litespeedtech/ols-docker-env#10]
@Code-Egg latest version is now 1.6.12, is there a way to automate this?

Thanks for the container it works really well now. I use it as a webserver and reverse proxy however using other docker containers such as wordpress or php that use FastCGI I can't find out how to set the `DOCUMENT_ROOT` or `SCRIPT_FILENAME` variables. The crux of the issue that the file path is different for say the php container and the OLS container.

**Comment by Code-Egg** [comment]
Hi @publicarray ,

Thanks for the great feedback.

About new version question. 
Right, we should have an automate method to build whenever openlitespeed release a new version. 
I may still need to add new version manually for now (will have the 1.6.12 ready today). If you found a new OLS release, you can also use the following method to upgrade to latest openlitespeed version. 
https://github.com/litespeedtech/ols-docker-env#update-web-server
`bash bin/webadmin.sh -U`

Do you mean that you are trying to use OLS as a proxy and other wordpress + PHP docker container can not working properly due to Document root set issue? but OLS already has a wordpress + PHP solution, isn't it? 

Best

**Comment by publicarray** [comment]
Thanks, I'm using docker a bit differently. Docker best practice is to have everything outside of docker containers. e.g. I pin the docker tag with the OLS version and update via `docker-compose up`

> OLS as a proxy and other wordpress + PHP docker container can not working properly due to Document root set issue?

precisely, and yes it does, but I have different applications each in a different containers like InvoiceNinja, WordPress and yourls. I've worked around it for the moment with various docker volumes but it's not suitable in the long run if I add more applications.

**Comment by Lars-Hagen** [comment]
> but I have different applications each in a different container like InvoiceNinja, WordPress and yourls. I've worked around it for the moment with various docker volumes but it's not suitable in the long run if I add more applications.

Hi @publicarray 

Would you be able to show us an example of this setup, and perhaps explain what issues you are running into and why its not suitable?

Best Regards
Lars
