### ISSUE TITLE
Change default location of the index.php

### ISSUE THREAD

**Issue by ltroya-as** [litespeedtech/ols-docker-env#39]
Hello guys, 

I am trying to run an existing bedrock wordpress project using this docker configuration. That means, the `index.php` is not located on the root of the project but `src/web/index.php`. 

I am wondering if it is possible to change it?

I added this configuration to the `.htaccess` but it is not working:

```
RewriteEngine on
RewriteCond %{HTTP_HOST} ^benchmark.test$ [NC,OR]
RewriteCond %{REQUEST_URI} !src/web/
RewriteRule (.*) src/web/$1 [L]
```

`benchmark.test` is my local domain. Is it the right place? :thinking: 

Thanks in advance!

**Comment by ltroya-as** [comment]
I can see the rewrite enable on the config files:
```
rewrite  {
    enable                1
    autoLoadHtaccess      1    
    logLevel              0
  }
  ```
  Not sure why it is not working

**Comment by Code-Egg** [comment]
The rewrite should work by default, you can enable the rewrite log via web admin> virtual host > rewrite > Log level to verify the rewrite from the error log. Since I'm not sure if this is how custom the index.php location method, you should check the error log and see if it's something else that caused the page is not to work and share here.

**Comment by ltroya-as** [comment]
@Code-Egg 

Oh, I didn't know all the vhosts were under the `VHost Templates > docker` option. I found the `Document Root` under that option. 

I only have one record under the `Virtual Host` sidebar option, that is `Example`. I see an open issue related to that #6.

Thanks for the hints!
