### ISSUE TITLE
Reverse proxy for Elastic Search

### ISSUE THREAD

**Issue by isvaljek** [litespeedtech/ols-docker-env#41]
I'm trying to figure out why my VHOST with Proxy context always returns 404, even though I can wget from the OLS container to the elasticsearch container on port 9200.

```
docRoot                   $VH_ROOT/html/
vhDomain                  elastic.test

errorlog $VH_ROOT/logs/$VH_NAME {
  useServer               1
  logLevel                ERROR
}

accesslog $SERVER_ROOT/logs/$VH_NAME.access.log {
  useServer               0
  rollingSize             100M
}

extprocessor elastic {
  type                    proxy
  address                 http://elasticsearch:9200
  maxConns                500
  pcKeepAliveTimeout      60
  initTimeout             60
  retryTimeout            0
  respBuffer              0
}

context / {
  type                    proxy
  handler                 elastic
  addDefaultCharset       off
}

rewrite  {
  logLevel                0
}
```

**Comment by Code-Egg** [comment]
This is my setup for PHPMyAdmin proxy, just a quick test and it works. Refer 
 https://docs.openlitespeed.org/docs/advanced/proxy#ip-based-virtual-hosting 

Server Configuration > External App
**Name**: `phpmyadmin`
**Address**: `http://1.2.3.4:8080`

VHost Template docker > Rewrite
```
REWRITERULE ^/phpmyadmin/(.*)$ HTTP://phpmyadmin/$1 [P]
```

Feel free to substitute VHost Template docker to the Virtual Host Example if you want to use Vhost indeed of the default Vhost template. 

You can ask on the OLS forum for more questions since I may not check GitHub issues that often.
