### ISSUE TITLE
Wp-config insecure secrets

### ISSUE THREAD

**Issue by xxxcrow** [litespeedtech/ols-docker-env#60]
If I check wp-config.php of my WordPress installation it some lines that I'm not sure are very secure:
```
define( 'AUTH_KEY',         'put your unique phrase here' );
define( 'SECURE_AUTH_KEY',  'put your unique phrase here' );
define( 'LOGGED_IN_KEY',    'put your unique phrase here' );
define( 'NONCE_KEY',        'put your unique phrase here' );
define( 'AUTH_SALT',        'put your unique phrase here' );
define( 'SECURE_AUTH_SALT', 'put your unique phrase here' );
define( 'LOGGED_IN_SALT',   'put your unique phrase here' );
define( 'NONCE_SALT',       'put your unique phrase here' );
```

**Comment by Code-Egg** [comment]
Hi,
Security Keys in WordPress are a string of random characters used for authorization and encryption of cookies generated by WordPress. During initial installation, it is not necessary for a user to provide these keys to install or run WordPress. If a user does not provide these keys in their wp-config.php file, then WordPress automatically generates these keys.
[Refer](https://www.wpbeginner.com/glossary/security-keys/)
Since it's not an issue, so close the ticket.

**Comment by xxxcrow** [comment]
@Code-Egg so to "not provide" those keys I need to put "put your unique phrase here" in my wp-config.php?

**Comment by Code-Egg** [comment]
HiHi, if you don't need it, just leave it as what it is.
