### ISSUE TITLE
WARN[0000] /home/docker-compose.yml: `version` is obsolete

### ISSUE THREAD

**Issue by nguyenthaiau** [litespeedtech/ols-docker-env#76]
Hello, the script is running very smooth, but today, i just reinstall vps and see a notice after run this script again
what's happen? how do i can resolve this? thanks.

`WARN[0000] /home/docker-compose.yml: `version` is obsolete`

**Comment by Code-Egg** [comment]
It seems like the warning happens after docker version 2.25.0, see https://github.com/jasonacox/Powerwall-Dashboard/issues/453 for the detail. 
To get rid of the warning, you can comment out the version from the compose file. Since it won't cause any trouble yet, I will keep it for a little bit longer.
